resources:
  Dbp\Relay\SublibraryBundle\ApiPlatform\Book:
    security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
    types: ['http://schema.org/Book']
    description: "A book from the library"
    shortName: "LibraryBook"
    routePrefix: "/sublibrary"
    normalizationContext:
      groups: ["LibraryBook:output"]
      jsonld_embed_context: true

    operations:

      ApiPlatform\Metadata\GetCollection:
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\BookProvider
        uriTemplate: "/books"
        openapiContext:
          tags: ["Sublibrary"]

      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\BookProvider
        uriTemplate: "/books/{identifier}"
        openapiContext:
          tags: ["Sublibrary"]

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      title:
        iri: "http://schema.org/name"
      isbn:
        iri: "http://schema.org/isbn"
      author:
        iri: "https://schema.org/author"
      publisher:
        iri: "https://schema.org/publisher"
      datePublished:
        iri: "https://schema.org/DateTime"

  Dbp\Relay\SublibraryBundle\Entity\Sublibrary:
    types: ['https://schema.org/Library']
    description: "Library of an Organization"
    shortName: "Sublibrary"
    routePrefix: "/sublibrary"
    normalizationContext:
      groups: ["Sublibrary:output"]
      jsonld_embed_context: true

    operations:

      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\SublibraryProvider
        uriTemplate: "/sublibraries"
        openapiContext:
          tags: ["Sublibrary"]
          parameters:
            - name: libraryManager
              in: query
              description: 'Get the Sublibraries the given person has library manager permissions for (ID of BasePerson resource)'
              required: true
              type: "string"
              example: "woody007"
            - name: lang
              in: query
              description: 'Language of result'
              required: false
              type: "string"
              enum: ["de", "en"]
              example: "de"

      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\SublibraryProvider
        uriTemplate: "/sublibraries/{identifier}"
        openapiContext:
          tags: ["Sublibrary"]
          parameters:
            - name: identifier
              in: path
              description: 'ID of Sublibrary'
              required: true
              type: "string"
              example: "1190"
            - name: lang
              in: query
              description: 'Language of result'
              required: false
              type: "string"
              enum: ["de", "en"]
              example: "de"

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      name:
        iri: "http://schema.org/name"
      code:
        iri: "http://schema.org/identifier"

  Dbp\Relay\SublibraryBundle\ApiPlatform\BudgetMonetaryAmount:
    security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
    types: ['https://schema.org/MonetaryAmount']
    description: "A budget value of Sublibrary"
    shortName: "LibraryBudgetMonetaryAmount"
    routePrefix: "/sublibrary"
    normalizationContext:
      groups: ["LibraryBudgetMonetaryAmount:output"]
      jsonld_embed_context: true

    operations:

      ApiPlatform\Metadata\GetCollection:
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\BudgetMonetaryAmountProvider
        uriTemplate: "/budget-monetary-amounts"
        openapiContext:
          tags: ["Sublibrary"]
          parameters:
            - name: sublibrary
              in: query
              description: 'Get all budget values of a sublibrary (ID of Sublibrary resource)'
              required: true
              type: "string"
              example: "1190"

      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\BudgetMonetaryAmountProvider
        uriTemplate: "/budget-monetary-amounts/{identifier}"
        openapiContext:
          tags: ["Sublibrary"]

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      value:
        iri: "http://schema.org/value"
      currency:
        iri: "http://schema.org/currency"

  Dbp\Relay\SublibraryBundle\ApiPlatform\EventStatusType:
    security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
    types: ['https://schema.org/EventStatusType']
    description: "A event status type"
    shortName: "EventStatusType"
    routePrefix: "/sublibrary"
    normalizationContext:
      groups: ["LibraryBookOrder:output"]
      jsonld_embed_context: true

    operations:

      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\DummyProvider
        uriTemplate: "/event-status-types/{identifier}"
        openapiContext:
          tags: ["Sublibrary"]

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      name:
        iri: "http://schema.org/name"

  Dbp\Relay\SublibraryBundle\ApiPlatform\DeliveryEvent:
    security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
    types: ['http://schema.org/DeliveryEvent']
    description: "A delivery status"
    shortName: "DeliveryStatus"
    routePrefix: "/sublibrary"
    normalizationContext:
      groups: ["LibraryBookOrder:output"]
      jsonld_embed_context: true

    operations:

      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\DummyProvider
        uriTemplate: "/delivery-statuses/{identifier}"
        openapiContext:
          tags: ["Sublibrary"]

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      availableFrom:
        iri: "http://schema.org/DateTime"
      eventStatus:
        iri: "http://schema.org/EventStatusType"

  Dbp\Relay\SublibraryBundle\ApiPlatform\ParcelDelivery:
    security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
    types: ['http://schema.org/ParcelDelivery']
    description: "A parcel delivery"
    shortName: "ParcelDelivery"
    routePrefix: "/sublibrary"
    normalizationContext:
      groups: ["LibraryBookOrder:output"]
      jsonld_embed_context: true

    operations:

      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\DummyProvider
        uriTemplate: "/parcel-deliveries/{identifier}"
        openapiContext:
          tags: ["Sublibrary"]

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      deliveryStatus:
        iri: "http://schema.org/DeliveryEvent"

  Dbp\Relay\SublibraryBundle\ApiPlatform\BookOrderItem:
    security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
    types: ['http://schema.org/OrderItem']
    description: "A book order item from the library"
    shortName: "LibraryBookOrderItem"
    routePrefix: "/sublibrary"
    normalizationContext:
      groups: ["LibraryBookOrder:output"]
      jsonld_embed_context: true

    operations:

      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\DummyProvider
        uriTemplate: "/book-order-items/{identifier}"
        openapiContext:
          tags: ["Sublibrary"]

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      orderedItem:
        iri: "http://schema.org/OrderItem"
      orderDelivery:
        iri: "http://schema.org/ParcelDelivery"
      price:
        iri: "http://schema.org/price"
      priceCurrency:
        iri: "http://schema.org/priceCurrency"

  Dbp\Relay\SublibraryBundle\ApiPlatform\BookOrder:
    security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
    types: ['http://schema.org/Order']
    description: "A book order from the library"
    shortName: "LibraryBookOrder"
    routePrefix: "/sublibrary"
    normalizationContext:
      groups: ["LibraryBookOrder:output"]
      jsonld_embed_context: true

    operations:

      ApiPlatform\Metadata\GetCollection:
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\BookOrderProvider
        uriTemplate: "/book-orders"
        openapiContext:
          tags: ["Sublibrary"]
          parameters:
            - name: sublibrary
              in: query
              description: 'Get all book offers of a sublibrary (ID of Sublibrary resource)'
              required: true
              type: "string"
              example: "1190"

      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\BookOrderProvider
        uriTemplate: "/book-orders/{identifier}"
        openapiContext:
          tags: ["Sublibrary"]

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      orderNumber:
        iri: "http://schema.org/orderNumber"
      receivingNote:
        iri: "http://schema.org/Text"
      orderedItem:
        iri: "http://schema.org/OrderItem"
      orderStatus:
        iri: "http://schema.org/Text"
      orderDate:
        iri: "http://schema.org/DateTime"

  Dbp\Relay\SublibraryBundle\ApiPlatform\BookLocation:
    security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
    types: ['https://schema.org/location']
    description: "The location, where a book is shelved."
    shortName: "BookLocation"
    routePrefix: "/sublibrary"
    normalizationContext:
      groups: ["BookLocation:output"]
      jsonld_embed_context: true

    operations:

      ApiPlatform\Metadata\GetCollection:
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\DummyProvider
        uriTemplate: "/book-locations"
        openapiContext:
          tags: ["Sublibrary"]

      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\DummyProvider
        uriTemplate: "/book-locations/{identifier}"
        openapiContext:
          tags: ["Sublibrary"]

      get_location_identifiers:
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_LIBRARY_MANAGER')"
        class: ApiPlatform\Metadata\GetCollection
        method: GET
        controller: Dbp\Relay\SublibraryBundle\ApiPlatform\GetLocationIdentifiersByBookOffer
        uriTemplate: "/book-offers/{identifier}/location-identifiers"
        read: false
        openapiContext:
          tags: ["Sublibrary"]
          summary: "Retrieves all location identifiers with in the same holding and with the same location as the book offer."
          parameters:
            - name: identifier
              in: path
              description: 'Id of book offer'
              type: string
              required: true

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
