resources:

  Dbp\Relay\SublibraryBundle\ApiPlatform\BookOrder:
    types: ['http://schema.org/Order']
    description: "A book order from the library"
    shortName: "LibraryBookOrder"
    routePrefix: "/sublibrary"
    normalizationContext:
      groups: ["LibraryBookOrder:output"]
      jsonld_embed_context: true

    operations:

      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\BookOrderProvider
        uriTemplate: "/book-orders"
        openapiContext:
          tags: ["Sublibrary"]
          parameters:
            - name: sublibrary
              in: query
              description: 'Get all book offers of a sublibrary (ID of Sublibrary resource)'
              required: true
              type: "string"
              example: "1190"

      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\BookOrderProvider
        uriTemplate: "/book-orders/{identifier}"
        openapiContext:
          tags: ["Sublibrary"]

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      orderNumber:
        iri: "http://schema.org/orderNumber"
      receivingNote:
        iri: "http://schema.org/Text"
      orderedItem:
        iri: "http://schema.org/OrderItem"
      orderStatus:
        iri: "http://schema.org/Text"
      orderDate:
        iri: "http://schema.org/DateTime"

  Dbp\Relay\SublibraryBundle\ApiPlatform\BookLocation:
    types: ['https://schema.org/location']
    description: "The location, where a book is shelved."
    shortName: "BookLocation"
    routePrefix: "/sublibrary"
    normalizationContext:
      groups: ["BookLocation:output"]
      jsonld_embed_context: true

    operations:

      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\DummyProvider
        uriTemplate: "/book-locations"
        openapiContext:
          tags: ["Sublibrary"]

      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\DummyProvider
        uriTemplate: "/book-locations/{identifier}"
        openapiContext:
          tags: ["Sublibrary"]

      get_location_identifiers:
        class: ApiPlatform\Metadata\GetCollection
        method: GET
        controller: Dbp\Relay\SublibraryBundle\ApiPlatform\GetLocationIdentifiersByBookOffer
        uriTemplate: "/book-offers/{identifier}/location-identifiers"
        read: false
        openapiContext:
          tags: ["Sublibrary"]
          summary: "Retrieves all location identifiers with in the same holding and with the same location as the book offer."
          parameters:
            - name: identifier
              in: path
              description: 'Id of book offer'
              type: string
              required: true

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"

  Dbp\Relay\SublibraryBundle\ApiPlatform\BookOffer:
    types: ['http://schema.org/Offer']
    description: "A book to lend from the library"
    shortName: "LibraryBookOffer"
    routePrefix: "/sublibrary"
    normalizationContext:
      groups: ["LibraryBook:output", "LibraryBookOffer:output"]
      jsonld_embed_context: true
    denormalizationContext:
      groups: ["LibraryBookOffer:input"]

    operations:

      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\BookOfferProvider
        uriTemplate: "/book-offers"
        openapiContext:
          tags: ["Sublibrary"]
          parameters:
            - name: barcode
              in: query
              description: 'Search for a book offer by barcode'
              type: string
            - name: sublibrary
              in: query
              description: 'Get all book offers of a sublibrary (ID of Sublibrary resource)'
              type: string
              example: '1190'

      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\BookOfferProvider
        uriTemplate: "/book-offers/{identifier}"
        openapiContext:
          tags: ["Sublibrary"]

      ApiPlatform\Metadata\Patch:
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\BookOfferProvider
        processor: Dbp\Relay\SublibraryBundle\ApiPlatform\BookOfferProcessor
        uriTemplate: "/book-offers/{identifier}"
        inputFormats:
          jsonld: [ 'application/merge-patch+json' ]
        openapiContext:
          tags: ["Sublibrary"]

      post_return:
        class: ApiPlatform\Metadata\Post
        method: POST
        controller: Dbp\Relay\SublibraryBundle\ApiPlatform\BookOfferPostReturn
        uriTemplate: "/book-offers/{identifier}/return"
        read: false
        write: false
        deserialize: false
        validate: false
        openapiContext:
          tags: ["Sublibrary"]
          summary: "Return a book offer."
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: "object"
                  example: '{}'
          parameters:
            - name: identifier
              in: path
              description: "Id of book offer"
              required: true
              type: string
              example: "991293320000541-2280429390003340-2380429400003340"

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      book:
        iri: "http://schema.org/Book"
      barcode:
        iri: "http://schema.org/serialNumber"
      locationIdentifier:
        iri: "http://schema.org/Text"
      library:
        iri: "http://schema.org/Text"
      location:
        iri: "http://schema.org/Text"
      description:
        iri: "http://schema.org/description"
      availabilityStarts:
        iri: "http://schema.org/availabilityStarts"
      name:
        iri: "http://schema.org/name"

  Dbp\Relay\SublibraryBundle\ApiPlatform\BookLoan:
    types: ['http://schema.org/LendAction']
    description: "A book loan in the library"
    shortName: "LibraryBookLoan"
    routePrefix: "/sublibrary"
    normalizationContext:
      groups: ["LibraryBookLoan:output", "BasePerson:output", "LibraryBookOffer:output", "LibraryBook:output", "LocalData:output"]
      jsonld_embed_context: true
    denormalizationContext:
      groups: ["LibraryBookLoan:input"]

    operations:

      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\BookLoanProvider
        uriTemplate: "/book-loans"
        openapiContext:
          tags: ["Sublibrary"]
          parameters:
            - name: borrower
              in: query
              description: 'Get all book loans of a borrower (ID of BasePerson resource)'
              type: string
              example: 'woody007'
            - name: sublibrary
              in: query
              description: 'Get all book offers of a sublibrary (ID of Sublibrary resource)'
              type: string
              example: '1190'

      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\BookLoanProvider
        uriTemplate: "/book-loans/{identifier}"
        openapiContext:
          tags: ["Sublibrary"]

      ApiPlatform\Metadata\Patch:
        provider: Dbp\Relay\SublibraryBundle\ApiPlatform\BookLoanProvider
        processor: Dbp\Relay\SublibraryBundle\ApiPlatform\BookLoanProcessor
        uriTemplate: "/book-loans/{identifier}"
        inputFormats:
          jsonld: ['application/merge-patch+json']
        openapiContext:
          tags: ["Sublibrary"]

      get_loans_by_book_offer:
        class: ApiPlatform\Metadata\GetCollection
        method: GET
        controller: Dbp\Relay\SublibraryBundle\ApiPlatform\GetBookLoansByBookOffer
        uriTemplate: "/book-offers/{identifier}/loans"
        read: false
        paginationEnabled: false
        normalizationContext:
          groups: ["LibraryBookLoan:output", "LibraryBookOffer:output", "LibraryBook:output"]
          jsonld_embed_context: true
        openapiContext:
          tags: ["Sublibrary"]
          summary: "Get the loans on a book offer."
          parameters:
            - name: identifier
              in: path
              description: 'Id of book offer'
              type: string
              required: true
              example: "991293320000541-2280429390003340-2380429400003340"

      post_loan_by_book_offer:
        class: ApiPlatform\Metadata\Post
        method: POST
        controller: Dbp\Relay\SublibraryBundle\ApiPlatform\PostBookLoanByBookOffer
        uriTemplate: "/book-offers/{identifier}/loans"
        read: false
        write: false
        deserialize: false
        validate: false
        openapiContext:
          tags: ["Sublibrary"]
          summary: "Post a loan for a book offer."
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: "object"
                  example:
                    borrower: "/base/people/woody007"
                    library: "F1490"
          parameters:
            - name: identifier
              in: path
              description: "Id of book offer"
              required: true
              type: string
              example: "991293320000541-2280429390003340-2380429400003340"

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      object:
        iri: "http://schema.org/Offer"
      borrower:
        iri: "http://schema.org/Person"
      startTime:
        iri: "https://schema.org/DateTime"
      endTime:
        iri: "https://schema.org/DateTime"
      returnTime:
        iri: "https://schema.org/DateTime"
      loanStatus:
        iri: "http://schema.org/Text"
