services:
    DBP\API\AlmaBundle\Service\AlmaApi:
        public: false
        autowire: true

    DBP\API\AlmaBundle\Service\LDAPApi:
        autowire: true
        autoconfigure: true

    DBP\API\AlmaBundle\Controller\:
        resource: '../../Controller'
        autowire: true
        autoconfigure: true

    DBP\API\AlmaBundle\DataPersister\:
        resource: '../../DataPersister'
        autowire: true
        autoconfigure: true

    DBP\API\AlmaBundle\DataProvider\:
        resource: '../../DataProvider'
        autowire: true
        autoconfigure: true

    DBP\API\AlmaBundle\Serializer\PersonNormalizer:
        autowire: true
        autoconfigure: true
