services:
    Dbp\Relay\SublibraryBundle\Service\AlmaApi:
        public: false
        autowire: true

    Dbp\Relay\SublibraryBundle\Service\LDAPApi:
        autowire: true
        autoconfigure: true

    Dbp\Relay\SublibraryBundle\Controller\:
        resource: '../../Controller'
        autowire: true
        autoconfigure: true

    Dbp\Relay\SublibraryBundle\DataPersister\:
        resource: '../../DataPersister'
        autowire: true
        autoconfigure: true

    Dbp\Relay\SublibraryBundle\DataProvider\:
        resource: '../../DataProvider'
        autowire: true
        autoconfigure: true

    Dbp\Relay\SublibraryBundle\Service\DummySublibraryProvider:
        autowire: true
        autoconfigure: true

    Dbp\Relay\SublibraryBundle\API\SublibraryProviderInterface:
        '@Dbp\Relay\SublibraryBundle\Service\DummySublibraryProvider'

    Dbp\Relay\SublibraryBundle\Service\HealthCheck:
        autowire: true
        autoconfigure: true
